# list

In [ ]:
lst_1 = ['banana', 'cherry', 'apple']

In [ ]:
lst_1

['banana', 'cherry', 'apple']

In [ ]:
lst_2 = []
lst_2

[]

In [ ]:
lst_3 = list()
lst_3

[]

In [ ]:
lst_4 = [5, True, 'apple', 5]
lst_4

[5, True, 'apple', 5]

In [ ]:
lst_1[0]

'banana'

In [ ]:
lst_1[-1]

'apple'

In [ ]:
print(lst_1)
item = lst_1[2]
print(item)

lst_1[2] = 'avocado'
print(lst_1)

['banana', 'cherry', 'apple']
apple
['banana', 'cherry', 'avocado']


In [ ]:
len(lst_1)

3

In [ ]:
print(lst_1)
lst_1.append('orange')
print(lst_1)

['banana', 'cherry', 'avocado']
['banana', 'cherry', 'avocado', 'orange']


In [ ]:
print(lst_1)
lst_1.insert(0,'grape')
print(lst_1)

['banana', 'cherry', 'avocado', 'orange']
['grape', 'banana', 'cherry', 'avocado', 'orange']


In [ ]:
item_poped = lst_1.pop()

In [ ]:
print(lst_1)
print(item_poped)

['grape', 'banana', 'cherry', 'avocado']
orange


In [ ]:
print(lst_1)
lst_1.remove('cherry')
print(lst_1)

['grape', 'banana', 'cherry', 'avocado']
['grape', 'banana', 'avocado']


In [ ]:
print(lst_1)
lst_1.clear()
print(lst_1)

['grape', 'banana', 'avocado']
[]


In [ ]:
my_lst = ['banana', 'cherry', 'apple']
my_lst

['banana', 'cherry', 'apple']

In [ ]:
my_lst.reverse()
my_lst

['apple', 'cherry', 'banana']

In [ ]:
my_lst = ['banana', 'cherry', 'apple']
my_lst

['banana', 'cherry', 'apple']

In [ ]:
my_lst.sort()
my_lst

['apple', 'banana', 'cherry']

In [ ]:
my_lst = ['banana', 'cherry', 'apple']
print(my_lst)

lst_sorted = sorted(my_lst)
print(lst_sorted)

['banana', 'cherry', 'apple']
['apple', 'banana', 'cherry']


In [ ]:
lst_0s = [0] * 5
lst_0s

[0, 0, 0, 0, 0]

In [ ]:
lst_concat = lst_0s + my_lst
lst_concat

[0, 0, 0, 0, 0, 'banana', 'cherry', 'apple']

In [ ]:
str_to_lst = list('Hello')
print(str_to_lst)

['H', 'e', 'l', 'l', 'o']


In [ ]:
lst_orginal = ['banana', 'cherry', 'apple']

In [ ]:
lst_copied = lst_orginal

In [ ]:
lst_copied.append(True)
print(lst_orginal)
print(lst_copied)

['banana', 'cherry', 'apple', True]
['banana', 'cherry', 'apple', True]


In [ ]:
lst_org = ["banana", "cherry", "apple"]

lst_copy_1 = lst_org.copy()
lst_copy_2 = list(lst_org)
lst_copy_3 = lst_org[:]

print(lst_copy_1)
print(lst_copy_2)
print(lst_copy_3)

['banana', 'cherry', 'apple']
['banana', 'cherry', 'apple']
['banana', 'cherry', 'apple']


In [ ]:
for i in lst_org:
  print(i)

banana
cherry
apple


In [ ]:
if 'banana' in lst_org:
  print('yes')
else:
  print('no')

yes


In [ ]:
a = list(range(1, 11))
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
b = a[1:3]
b

[2, 3]

In [ ]:
a[::-1]

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [ ]:
b = [x**2 for x in a]
b

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

# tuple

In [ ]:
tup_1 = ('Max')
type(tup_1)

str

In [ ]:
tup_2 = ('Max',)
type(tup_2)

tuple

In [ ]:
tup_3 = ('Mad', 'Max')
print(type(tup_3))
print(tup_3)

<class 'tuple'>
('Mad', 'Max')


In [ ]:
tup_4 = tuple(['Max'])
print(type(tup_4))
print(tup_4)

<class 'tuple'>
('Max',)


In [ ]:
if 'Max' in tup_3:
  print('Yes')
else:
  print('No')

Yes


In [ ]:
tup_apple = ('a', 'p', 'p', 'l', 'e')

In [ ]:
len(tup_apple)

5

In [ ]:
tup_apple.count('p')

2

In [ ]:
tup_apple.index('p')

1

In [ ]:
lst_apple = list(tup_apple)
lst_apple

['a', 'p', 'p', 'l', 'e']

In [ ]:
tup_apple_back = tuple(lst_apple)
tup_apple_back

('a', 'p', 'p', 'l', 'e')

In [ ]:
tup_profile = 'Max', 28, 'ChengDu'

In [ ]:
Name, Age, City = tup_profile
print(Name, Age, City)

Max 28 ChengDu


In [ ]:
tup_num = (0, 1, 2, 3, 4)

In [ ]:
i1, *i2, i3 = tup_num
print(i1, i2, i3)

0 [1, 2, 3] 4


In [ ]:
import sys

lst = [0, 1, 2, 'Hello', True]
tup = (0, 1, 2, 'Hello', True)

print(sys.getsizeof(lst), 'bytes')
print(sys.getsizeof(tup), 'bytes')

112 bytes
96 bytes


In [ ]:
import timeit

print(timeit.timeit(stmt="[0,1,2,3,4,5]", number=1000000))     # stmt: statement 
print(timeit.timeit(stmt="(0,1,2,3,4,5)", number=1000000))

0.09102445100006662
0.013938993000010669


# dict

In [ ]:
dict_1 = {'name': 'Sarah', 'age': 33, 'city': 'CD'}
dict_1

{'age': 33, 'city': 'CD', 'name': 'Sarah'}

In [ ]:
dict_2 = dict(name='Mary', age=27, city='LZ')
dict_2

{'age': 27, 'city': 'LZ', 'name': 'Mary'}

In [ ]:
dict_1['phone'] = 13139276898

In [ ]:
dict_1

{'age': 33, 'city': 'CD', 'name': 'Sarah', 'phone': 13139276898}

In [ ]:
dict_1['phone'] = '+86-13139276898'

In [ ]:
dict_1

{'age': 33, 'city': 'CD', 'name': 'Sarah', 'phone': '+86-13139276898'}

In [ ]:
del dict_1['phone']
dict_1

{'age': 33, 'city': 'CD', 'name': 'Sarah'}

In [ ]:
dict_1.pop('age')
dict_1

{'city': 'CD', 'name': 'Sarah'}

In [ ]:
if 'name' in dict_1:
  print(dict_1['name'])

Sarah


In [ ]:
try:
  print(dict_1['name'])
except:
  print('error')

Sarah


In [ ]:
try:
  print(dict_1['last_name'])
except:
  print('error')

error


In [ ]:
dict_1_copy = dict_1

In [ ]:
dict_1

{'city': 'CD', 'name': 'Sarah'}

In [ ]:
dict_1_copy

{'city': 'CD', 'name': 'Sarah'}

In [ ]:
dict_1_copy['city'] = 'Chicago'

In [ ]:
dict_1

{'city': 'Chicago', 'name': 'Sarah'}

In [ ]:
dict_1_deep_copy_1 = dict_1.copy()
dict_1_deep_copy_1

{'city': 'Chicago', 'name': 'Sarah'}

In [ ]:
dict_1_deep_copy_1['name'] = 'Bo'

In [ ]:
dict_1

{'city': 'Chicago', 'name': 'Sarah'}

In [ ]:
dict_1_deep_copy_2 = dict(dict_1)

In [ ]:
dict_1_deep_copy_2

{'city': 'Chicago', 'name': 'Sarah'}

In [ ]:
dict_1

{'city': 'Chicago', 'name': 'Sarah'}

In [ ]:
dict_1_deep_copy_2['name'] = 'Eddie'

In [ ]:
dict_1_deep_copy_2

{'city': 'Chicago', 'name': 'Eddie'}

In [ ]:
dict_1

{'city': 'Chicago', 'name': 'Sarah'}

In [ ]:
dict_1.update(dict_2)

In [ ]:
dict_1

{'age': 27, 'city': 'LZ', 'name': 'Mary'}

In [ ]:
tup = (8, 7)                      # if it's list, can't work cuz list is mutable
dict_3 = {tup: tup[0] + tup[1]}
dict_3

{(8, 7): 15}

# set

In [ ]:
set_1 = {1, 2, 2, 4, 6}
set_1

{1, 2, 4, 6}

In [ ]:
set_2 = set('Hello')
set_2

{'H', 'e', 'l', 'o'}

In [ ]:
set_3 = {}
type(set_3)

dict

In [ ]:
set_4 = set()
print(type(set_4))

<class 'set'>


In [ ]:
print(set_4)
set_4.add(3)
set_4.add(1)
print(set_4)

set()
{1, 3}


In [ ]:
set_4.remove(3)      # when no removed element there, it raises error 
set_4

{1}

In [ ]:
set_2

{'H', 'e', 'l', 'o'}

In [ ]:
set_2.discard('e')
set_2

{'H', 'l', 'o'}

In [ ]:
set_2.discard('aa')
set_2

{'H', 'l', 'o'}

In [ ]:
set_2.pop()         #  arbitrarily remove
set_2

{'l', 'o'}

In [ ]:
odds = {1, 3, 5, 7, 9}
evens = {0, 2, 4, 6, 8}
primes = {2, 3, 5, 7}

In [ ]:
u = odds.union(evens)
u

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [ ]:
inter = odds.intersection(evens)
inter

set()

In [ ]:
odds.intersection(primes)

{3, 5, 7}

In [ ]:
set_A = {1, 2, 3, 4, 5, 6, 7, 8, 9}
set_B = {1, 2, 3, 10, 11, 12}

In [ ]:
diff = set_A.difference(set_B)
diff

{4, 5, 6, 7, 8, 9}

In [ ]:
diff_sym = set_A.symmetric_difference(set_B)
diff_sym

{4, 5, 6, 7, 8, 9, 10, 11, 12}

In [ ]:
set_A.update(set_B)
set_A

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}

In [ ]:
set_A.intersection_update(set_B)
set_A

{1, 2, 3, 10, 11, 12}

In [ ]:
set_A.difference_update(set_B)
set_A

set()

In [ ]:
set_C = {1, 2, 3, 4, 5, 6, 7, 8, 9}
set_D = {1, 2, 3}

In [ ]:
set_C.issubset(set_D)

False

In [ ]:
set_D.issubset(set_C)

True

In [ ]:
set_C.issuperset(set_D)

True

In [ ]:
set_C.isdisjoint(set_D)

False

In [ ]:
fset = frozenset([1,2,3,4])          # immutable version of set

In [ ]:
fset

frozenset({1, 2, 3, 4})

# string

In [ ]:
str_1 = 'I\'m a nerd'   escaping backslash        
str_1 

"I'm a nerd"

In [ ]:
str_2 = '''hello 
wolrd'''
print(str_2)

hello 
wolrd


In [ ]:
str_3 = '''halo \
wala'''
print(str_3)

halo wala


In [ ]:
str_4 = 'olleH'
print(str_4[::-1])

Hello


In [ ]:
str_5 = '   Hello'
print(str_5)

   Hello


In [ ]:
str_5 = '   Hello'
print(str_5.strip())

Hello


In [ ]:
print(str_4)
print(str_4.startswith('H'))

olleH
False


In [ ]:
print(str_4)
print(str_4.startswith('o'))

olleH
True


In [ ]:
print(str_4)
print(str_4.endswith('H'))

olleH
True


In [ ]:
print(str_4)
print(str_4.find('e'))

olleH
3


In [ ]:
print(str_4)
print(str_4.find('u'))

olleH
-1


In [ ]:
print(str_4)
print(str_4.count('u'))

olleH
0


In [ ]:
print(str_4)
print(str_4.count('l'))

olleH
2


In [ ]:
str_6 = 'Hello World'

In [ ]:
print(str_6.replace('World', 'Uni'))
print(str_6)

Hello Uni
Hello World


In [ ]:
str_7 = str_6.split()
str_7

['Hello', 'World']

In [ ]:
str_8 = 'Hello,World,you,are,good'
print(str_8.split())
print(str_8.split(','))

['Hello,World,you,are,good']
['Hello', 'World', 'you', 'are', 'good']


In [ ]:
str_9 = str_8.split(',')
str_9

['Hello', 'World', 'you', 'are', 'good']

In [ ]:
str_10 = ''.join(str_9)
str_10

'HelloWorldyouaregood'

In [ ]:
str_11 = ' '.join(str_9)              # very important
str_11

'Hello World you are good'

In [ ]:
lst = ['a']*6

In [ ]:
str_12 = ''.join(lst)                # most efficient way of doing the job
print(str_12)

aaaaaa


## string-formatting

In [ ]:
var = 3.14156

In [ ]:
str_13 = "the variable is %f" % var      # first method: %s: str; %d: int; %f: float  
str_13

'the variable is 3.141560'

In [ ]:
str_14 = "the variable is {:.2f}".format(var)
str_14

'the variable is 3.14'

In [ ]:
str_15 = f"the variable is {var:.2f}"
str_15

'the variable is 3.14'

# collections

Counter, namedtuple, OrderedDict, defaultdict, deque

In [ ]:
from collections import Counter   # Counter is a container contains dict that stores dict keys and values

In [ ]:
a = 'aaaaabbbbccc'

In [ ]:
my_counter = Counter(a)
print(my_counter)

Counter({'a': 5, 'b': 4, 'c': 3})


In [ ]:
print(my_counter.items())

dict_items([('a', 5), ('b', 4), ('c', 3)])


In [ ]:
print(my_counter.keys())

dict_keys(['a', 'b', 'c'])


In [ ]:
print(my_counter.values())

dict_values([5, 4, 3])


In [ ]:
print(my_counter.most_common(1))

[('a', 5)]


In [ ]:
print(my_counter.most_common(2))

[('a', 5), ('b', 4)]


In [ ]:
print(my_counter.elements())

In [ ]:
print(list(my_counter.elements()))

['a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'c', 'c', 'c']


In [ ]:
from collections import namedtuple

In [ ]:
Point = namedtuple('Point', 'x, y')          #  Point is a class

In [ ]:
pt = Point(1, -4)

In [ ]:
print(pt)

Point(x=1, y=-4)


In [ ]:
print(pt.x, pt.y)

1 -4


In [ ]:
from collections import OrderedDict    # a regular dict but remembers order

In [ ]:
ordered_dict = OrderedDict()

In [ ]:
ordered_dict['a'] = 1
ordered_dict['b'] = 2
ordered_dict['c'] = 3
ordered_dict['d'] = 4

In [ ]:
print(ordered_dict)

OrderedDict([('a', 1), ('b', 2), ('c', 3), ('d', 4)])


In [ ]:
ordered_dict_1 = OrderedDict()

ordered_dict_1['b'] = 2
ordered_dict_1['c'] = 3
ordered_dict_1['d'] = 4
ordered_dict_1['a'] = 1

In [ ]:
print(ordered_dict_1)

OrderedDict([('b', 2), ('c', 3), ('d', 4), ('a', 1)])


In [ ]:
from collections import defaultdict   # a regular dict but gives a defult value if a key is not provided

In [ ]:
d = defaultdict(int)

In [ ]:
d['a'] = 1
d['b'] = 2

In [ ]:
print(d['b'])

2


In [ ]:
print(d['DDD'])       # no key, but returns a int 0

0


In [ ]:
from collections import deque   # double ended que, can be both ends

In [ ]:
d = deque()

In [ ]:
d.append(1)
d.append(2)
print(d)

deque([1, 2])


In [ ]:
d.appendleft(3)
print(d)

deque([3, 1, 2])


In [ ]:
d.pop()
print(d)

deque([3, 1])


In [ ]:
d.popleft()
print(d)

deque([1])


In [ ]:
d.extendleft([3,4,5])
print(d)

deque([5, 4, 3, 1])


In [ ]:
d.rotate(1)
print(d)

deque([3, 1, 5, 4])


In [ ]:
d.rotate(-1)
print(d)

deque([1, 5, 4, 3])


# itertools

itertools: product, permutations, combinations, accumulate, groupby, infinite iterators

In [ ]:
from itertools import product

In [ ]:
a = [1, 2]
b = [3, 4]

In [ ]:
prod = product(a, b)
print(prod)

In [ ]:
print(list(prod))

[(1, 3), (1, 4), (2, 3), (2, 4)]


In [ ]:
a = [1, 2]
b = [3]

prod_2 = product(a, b, repeat = 2)
print(list(prod_2))

[(1, 3, 1, 3), (1, 3, 2, 3), (2, 3, 1, 3), (2, 3, 2, 3)]


In [ ]:
from itertools import permutations

In [ ]:
a = [1, 2, 3]

In [ ]:
perm = permutations(a)
print(perm)

In [ ]:
print(list(perm))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [ ]:
perm_2 = permutations(a, 2)
print(list(perm_2))

[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]


In [ ]:
from itertools import combinations

In [ ]:
a = [1, 2, 3, 4]
comb = combinations(a, 2)
print(list(comb))

[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]


In [ ]:
from itertools import combinations, combinations_with_replacement

In [ ]:
a = [1, 2, 3, 4]
comb_wr = combinations_with_replacement(a, 2)
print(list(comb_wr))

[(1, 1), (1, 2), (1, 3), (1, 4), (2, 2), (2, 3), (2, 4), (3, 3), (3, 4), (4, 4)]


In [ ]:
from itertools import accumulate

In [ ]:
a = [1, 2, 3, 4]

In [ ]:
acc = accumulate(a)

In [ ]:
print(a)
print(list(acc))

[1, 2, 3, 4]
[1, 3, 6, 10]


In [ ]:
import operator

In [ ]:
acc_2 = accumulate(a, func = operator.mul)
print(a)
print(list(acc_2))

[1, 2, 3, 4]
[1, 2, 6, 24]


In [ ]:
a = [1, 2, 5, 3, 4]

acc_3 = accumulate(a, func = max)
print(a)
print(list(acc_3))

[1, 2, 5, 3, 4]
[1, 2, 5, 5, 5]


In [ ]:
from itertools import groupby

In [ ]:
def smaller_than_3(x):
  return x < 3

In [ ]:
a = [1, 2, 3, 4]
obj_group = groupby(a, key = smaller_than_3)

In [ ]:
for key, value in obj_group:
  print(key, list(value))

In [ ]:
persons = [{'name': 'Tim', 'age': 25},
       {'name': 'Dan', 'age': 25},
       {'name': 'Lisa', 'age': 27,},
       {'name': 'Clara', 'age': 28 }     ]

In [ ]:
group_obj = groupby(persons, key = lambda x: x['age'])

In [ ]:
for key, value in group_obj:
  print(key, list(value))

25 [{'name': 'Tim', 'age': 25}, {'name': 'Dan', 'age': 25}]
27 [{'name': 'Lisa', 'age': 27}]
28 [{'name': 'Clara', 'age': 28}]


In [ ]:
from itertools import count, cycle, repeat

In [ ]:
for i in count(10):
  print(i)
  if i == 15:
    break

10
11
12
13
14
15


In [ ]:
a = [1, 2, 3,]

In [ ]:
for i in cycle(a):
  print(i)
  if i == 3:
    break

1
2
3


In [ ]:
for i in repeat(1, 5):
  print(i)

1
1
1
1
1


# Lambda

lambda arguments: expression

In [ ]:
add_10 = lambda x: x + 10

In [ ]:
add_10(5)

15

In [ ]:
mult = lambda x, y: x * y 

In [ ]:
mult(3, 4)

12

In [ ]:
points_2D = [(1, 2), (15, 1), (5, -1), (10, 4)]

In [ ]:
points_2D_sorted = sorted(points_2D)

In [ ]:
print(points_2D)
print(points_2D_sorted)

[(1, 2), (15, 1), (5, -1), (10, 4)]
[(1, 2), (5, -1), (10, 4), (15, 1)]


In [ ]:
points_2D_sorted_y = sorted(points_2D, key = lambda x:x[1])

In [ ]:
print(points_2D_sorted_y)

[(5, -1), (15, 1), (1, 2), (10, 4)]


In [ ]:
points_2D_sorted_x_add_y = sorted(points_2D, key = lambda x : x[0] + x[1])

In [ ]:
print(points_2D_sorted_x_add_y)

[(1, 2), (5, -1), (10, 4), (15, 1)]


In [ ]:
a = [1, 2, 3, 4, 5]
b = map(lambda x : x*2, a)         # map 

In [ ]:
print(a)
print(list(b))

[1, 2, 3, 4, 5]
[2, 4, 6, 8, 10]


In [ ]:
b = [i*2 for i in a]
print(b)

[2, 4, 6, 8, 10]


In [ ]:
a = [1, 2, 3, 4, 5, 6]
b = filter(lambda x : x % 2 == 0, a)         # filter

In [ ]:
print(b)

[2, 4, 6, 8, 10]


In [ ]:
b = [i for i in a if i % 2 == 0]
print(b)

[2, 4, 6]


In [ ]:
from functools import reduce

In [ ]:
a = [1, 2, 3, 4]

In [ ]:
product_a = reduce(lambda x, y: x * y, a)    # 连乘？

In [ ]:
print(product_a)

24


# errors & exceptions

In [ ]:
x = -5

In [ ]:
if x < 0:
  raise Exception('x should be positive')

Exception: ignored

In [ ]:
assert (x >= 0)

AssertionError: ignored

In [ ]:
assert (x >= 0, 'x is not positive')

<ipython-input-36-cc346b5af0c0>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (x >= 0, 'x is not positive')


In [ ]:
try:
  a = 5 / 0
except:
  print('an error occurred')

an error occurred


In [ ]:
try:
  a = 5 / 0
except Exception as e:
  print(e)

division by zero


In [ ]:
try:
  a = 5 / 0
  b = a + '10'
except ZeroDivisionError as e_1:
  print(e_1)
except TypeError as e_2:
  print(e_2)
else:
  print('everything OK')
finally:
  print('cleaning up...')

division by zero
cleaning up...


In [ ]:
class ValueTooHighError(Exception):
  pass

In [ ]:
def test_value(x):
  if x > 100:
    raise ValueTooHighError('value too high')

In [ ]:
test_value(200)

ValueTooHighError: ignored

In [ ]:
try:
  test_value(200)
except ValueTooHighError as e:
  print(e)

value too high


In [ ]:
class ValueTooLowError(Exception):
  def __init__(self, message, value):
    self.message = message
    self.value = value

In [ ]:
def test_value(x):
  if x > 100:
    raise ValueTooHighError('value too high')
  if x < 5:
    raise ValueTooLowError('value too low')

In [ ]:
try:
  test_value(200)
except ValueTooHighError as e_1:
  print(e_1)
except ValueTooLowError as e_2:
  print(e_2)

value too high


# logging

In [ ]:
import logging

5 different levels of logging:

In [ ]:
logging.debug('This is a debug message')
logging.info('This is an info message')
logging.warning('This is a warning message')
logging.error('This is an error message')
logging.critical('This is a critical message')

ERROR:root:This is an error message
CRITICAL:root:This is a critical message


In [ ]:
logging.basicConfig(level = logging.DEBUG,
          format = '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
          dateformat = '%m/%d/%Y %H:%M:%S')  

In [ ]:
logging.debug('This is a debug message')
logging.info('This is an info message')
logging.warning('This is a warning message')
logging.error('This is an error message')
logging.critical('This is a critical message')

ERROR:root:This is an error message
CRITICAL:root:This is a critical message


# json

In [ ]:
import json

In [ ]:
person = {"name": "John", "age": 30, "city": "New York", 
      "hasChildren": False, "titles": ["engineer", "programmer"]}

In [ ]:
person_json = json.dumps(person)                # Serialization (encoding)

In [ ]:
print(person_json)

{"name": "John", "age": 30, "city": "New York", "hasChildren": false, "titles": ["engineer", "programmer"]}


In [ ]:
person_json_1 = json.dumps(person, indent = 4, sort_keys = True)

In [ ]:
person_json_1

'{\n    "age": 30,\n    "city": "New York",\n    "hasChildren": false,\n    "name": "John",\n    "titles": [\n        "engineer",\n        "programmer"\n    ]\n}'

In [ ]:
with open ('person.json', 'w') as file:
  json.dump(person, file, indent = 4)

In [ ]:
person_dict = json.loads(person_json)               # de-serialization (decoding)
print(person_dict)

{'name': 'John', 'age': 30, 'city': 'New York', 'hasChildren': False, 'titles': ['engineer', 'programmer']}


In [ ]:
person_loaded = json.loads(person_json)
print(person_loaded)

{'name': 'John', 'age': 30, 'city': 'New York', 'hasChildren': False, 'titles': ['engineer', 'programmer']}


In [ ]:
with open('person.json', 'r') as file:
  person = json.load(file)
  print(person)

{'name': 'John', 'age': 30, 'city': 'New York', 'hasChildren': False, 'titles': ['engineer', 'programmer']}


In [ ]:
class User():
  def __init__(self, name, age):
    self.name = name
    self.age = age

In [ ]:
user = User('Max', 27)

In [ ]:
user

In [ ]:
user_json = json.dumps(user)

TypeError: ignored

In [ ]:
def encode_user(o):
  if isinstance(o, User):
    return {'name': o.name,
         'age': o.age,
         o.__class__.__name__: True}
  else:
    raise TypeError('Obj of type User is not json serializable')

In [ ]:
user_json = json.dumps(user, default = encode_user)

In [ ]:
print(user_json)

{"name": "Max", "age": 27, "User": true}


Or:

In [ ]:
from json import JSONEncoder

In [ ]:
class UserEncoder(JSONEncoder):
  def default(self, o):
    if isinstance(o, User):
      return {'name': o.name,
           'age': o.age,
           o.__class__.__name__: True}
    return JSONEncoder.default(self, o)

In [ ]:
user_json_2 = UserEncoder().encode(user)
print(user_json_2)

{"name": "Max", "age": 27, "User": true}


In [ ]:
user = json.loads(user_json)
print(user)
print(type(user))

{'name': 'Max', 'age': 27, 'User': True}
<class 'dict'>


In [ ]:
def decode_user(dct):
  if User.__name__ in dct:
    return User(name = dct['name'], 
           age = dct['age'])
  return dct

In [ ]:
user = json.loads(user_json, object_hook = decode_user)

In [ ]:
print(user)
print(type(user))

<class '__main__.User'>


In [ ]:
user.name

'Max'

In [ ]:
user.age

27

# random numbers

In [ ]:
import random    # a module generate pesudo-random num, 'pesudo' means that it is random, but we can reproduce it

In [ ]:
a = random.random()      # a random float [0, 1]

In [ ]:
a

0.40747753585172464

In [ ]:
a = random.uniform(1, 10)
a  

1.5026552844444288

In [ ]:
a = random.randint(1, 10)
a  

10

In [ ]:
a = random.randrange(1, 10)   # excluded boundaries
a  

3

In [ ]:
a = random.normalvariate(0, 1)
a

-0.6037991775109214

In [ ]:
lst = list('ABCDEFGH')
lst

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [ ]:
a = random.choice(lst)
a

'D'

In [ ]:
a = random.sample(lst, 3)    # no-replacement
a

['C', 'B', 'E']

In [ ]:
a = random.choices(lst, k = 3)    # with replacement
a

['F', 'F', 'F']

In [ ]:
print(lst)
random.shuffle(lst)
print(lst)

['E', 'F', 'C', 'G', 'A', 'H', 'D', 'B']
['D', 'F', 'E', 'A', 'G', 'C', 'B', 'H']


In [ ]:
random.seed(1)
print(random.random())
print(random.randint(1, 10))

0.13436424411240122
2


In [ ]:
random.seed(1)                    # pesudo 
print(random.random())
print(random.randint(1, 10))

0.13436424411240122
2


In [ ]:
random.seed(42)                    # pesudo 
print(random.random())
print(random.randint(1, 10))

0.6394267984578837
1


In [ ]:
random.seed(42)                    # pesudo 
print(random.random())
print(random.randint(1, 10))

0.6394267984578837
1


pesudo: not suitable for security purpose

In [ ]:
import secrets    # for PW etc.

In [ ]:
a = secrets.randbelow(10)
print(a)

7


In [ ]:
a = secrets.randbits(4)   # max = 15
print(a)

13


In [ ]:
lst = list('ABCDEFGH')
a = secrets.choice(lst)
print(a)

G


In [ ]:
import numpy as np

In [ ]:
a = np.random.rand(3)
a

array([0.16345828, 0.2489448 , 0.82640235])

In [ ]:
a = np.random.rand(3,2)
a

array([[0.47207499, 0.57995195],
       [0.69562415, 0.37163898],
       [0.39090332, 0.94618814]])

In [ ]:
a = np.random.randint(0,10,3)
a

array([6, 2, 4])

In [ ]:
a = np.random.randint(0,10,(3, 2))
a

array([[1, 4],
       [5, 6],
       [9, 8]])

In [ ]:
arr = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

In [ ]:
print(arr)
print(np.random.shuffle(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
None


In [ ]:
np.random.seed(1)
a = np.random.randint(0,10,(3, 2))
a

array([[5, 8],
       [9, 5],
       [0, 0]])

In [ ]:
np.random.seed(1)
a = np.random.randint(0,10,(3, 2))
a

array([[5, 8],
       [9, 5],
       [0, 0]])

# decorators

https://www.python-engineer.com/courses/advancedpython/13-decorators/

decorator is a @"function" that takes another func as argument and extend the functionality of the function

two kinds of decorators: function decorator & class decorator

Format:

@mydecorator

def dosomething():
   pass

In [ ]:
def start_end_decorator(func):

  def wrapper(*args, **kwargs):
    print('Start')
    func(*args, **kwargs)
    print('End')
  return wrapper

In [ ]:
def print_name():
  print('Lin')

In [ ]:
name_strat_end = start_end_decorator(print_name)

In [ ]:
name_strat_end()

Start
Lin
End


Or, use @ decorator:

In [ ]:
@start_end_decorator
def print_name():
  print('Bo')

In [ ]:
print_name()

Start
Bo
End


In [ ]:
@start_end_decorator
def add5(x):
  print(x + 5)

In [ ]:
add5(10)

Start
15
End


In [ ]:
print(add5.__name__)                             # identity is confused
help(add5)

wrapper
Help on function wrapper in module __main__:

wrapper(*args, **kwargs)



In [ ]:
import functools      

def start_end_decorator_4(func):            
    
    @functools.wraps(func)                        # identity issue fixed
    def wrapper(*args, **kwargs):
        print('Start')
        result = func(*args, **kwargs)
        print('End')
        return result
    return wrapper

@start_end_decorator_4
def add_5(x):
    return x + 5
result = add_5(10)
print(result)
print(add_5.__name__)
help(add_5)

Start
End
15
add_5
Help on function add_5 in module __main__:

add_5(x)



In [ ]:
class CountCalls:

  def __init__(self, func):
    self.func = func
    self.num_calls = 0

  def __call__(self, *args, **kwargs):
    self.num_calls += 1
    print(f"This is called {self.num_calls} times")
    return self.func(*args, **kwargs)


In [ ]:
@CountCalls

def say_hello():
  print('Hello')

In [ ]:
say_hello()

This is called 1 times
Hello


In [ ]:
say_hello()

This is called 2 times
Hello


In [ ]:
say_hello()

This is called 3 times
Hello


# generators

Generators are functions that return an object that can be iterated over. They generate the object inside lazily, which means that it generate item one at a time and only only when you ask for it, which is memory efficient. 

Defined as a normal func but with a yield keyword instead of a return keyword

In [ ]:
def mygenerator():
  yield 1
  yield 2
  yield 3

In [ ]:
g = mygenerator()

In [ ]:
value = next(g)
print(value)

1


In [ ]:
print(value)

1


In [ ]:
value = next(g)
print(value)

3


In [ ]:
value = next(g)
print(value)

2


In [ ]:
value = next(g)
print(value)

StopIteration: ignored

In [ ]:
print(sum(g))

0


In [ ]:
def countdown(num):
  print('Start')
  while num > 0:
    yield num
    num -= 1

In [ ]:
cd = countdown(4)

In [ ]:
value = next(cd)
print(value)

Start
4


In [ ]:
value = next(cd)
print(value)

3


In [ ]:
value = next(cd)
print(value)

2


In [ ]:
value = next(cd)
print(value)

1


In [ ]:
value = next(cd)
print(value)

StopIteration: ignored

In [ ]:
import sys

In [ ]:
def firstn(n):
  nums = []
  num = 0
  while num < n:
    nums.append(num)
    num += 1
  return nums

In [ ]:
print(firstn(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
print(sum(firstn(10)))

45


In [ ]:
def firstn_generator(n):      # memory efficient
  num = 0 
  while num < n:
    yield num
    num += 1

In [ ]:
print(sum(firstn_generator(10)))

45


In [ ]:
print(sys.getsizeof(firstn(10)))
print(sys.getsizeof(firstn_generator(10)))

200
128


In [ ]:
print(sys.getsizeof(firstn(100000)))
print(sys.getsizeof(firstn_generator(100000)))

824472
128


In [ ]:
def fibonacci(limit):
  # 0 1 1 2 3 5 8 13
  a , b = 0, 1
  while a < limit:
    yield a
    a, b = b, a + b

In [ ]:
fib = fibonacci(10)

In [ ]:
for i in fib:
  print(i)

0
1
1
2
3
5
8


In [ ]:
mygenerator = (i for i in range(100000) if i % 2 == 0)     # likewise list comprehension but use ( ) instead of [ ]

In [ ]:
for i in mygenerator:
  print(i)
  break

0


In [ ]:
mylist = [i for i in range(100000) if i % 2 == 0]

In [ ]:
print(sys.getsizeof(mygenerator))
print(sys.getsizeof(mylist))

128
406504


# threading VS multiprocessing

A process can have multiple threads

We have two common approaches to run code in parallel (achieve multitasking and speed up your program) : via threads or via multiple processes.

### Process
A Process is an instance of a program, e.g. a Python interpreter. They are independent from each other and do not share the same memory.

Key facts: - A new process is started independently from the first process - Takes advantage of multiple CPUs and cores - Separate memory space - Memory is not shared between processes - One GIL (Global interpreter lock) for each process, i.e. avoids GIL limitation - Great for CPU-bound processing - Child processes are interruptable/killable

Starting a process is slower that starting a thread
Larger memory footprint
IPC (inter-process communication) is more complicated

### Threads
A thread is an entity within a process that can be scheduled for execution (Also known as "leightweight process"). A Process can spawn multiple threads. The main difference is that all threads within a process share the same memory.

Key facts: - Multiple threads can be spawned within one process - Memory is shared between all threads - Starting a thread is faster than starting a process - Great for I/O-bound tasks - Leightweight - low memory footprint

- One GIL for all threads, i.e. threads are limited by GIL - Multithreading has no effect for CPU-bound tasks due to the GIL - Not interruptible/killable -> be careful with memory leaks - increased potential for race conditions

In [ ]:
from multiprocessing import Process

In [ ]:
import os
import time

In [ ]:
def square_num():
  for i in range(100):
    i * i
    time.sleep(0.1)

In [ ]:
processes =[]
num_processes = os.cpu_count()

In [ ]:
for i in range(num_processes):
  p = Process(target = square_num)
  processes.append(p)

In [ ]:
for p in processes:
  p.start()

In [ ]:
for p in processes:
  p.join()

In [ ]:
print('end main')

end main


check task manager for details

In [ ]:
from threading import Thread

In [ ]:
import os
import time

In [ ]:
def square_num_2():
  for i in range(100):
    i * i
    time.sleep(0.1)

In [ ]:
threads = []
num_threads = 10

In [ ]:
for i in range(num_threads):
  t = Thread(target = square_num_2)
  threads.append(t)

In [ ]:
for t in threads:
  t.start()

In [ ]:
for t in threads:
  t.join()

In [ ]:
print('end main')

end main


### multi-threading:
https://www.python-engineer.com/courses/advancedpython/16-threading/

```
# 此内容为代码格式
```



### multi-processing:
https://www.python-engineer.com/courses/advancedpython/17-multiprocessing/

In [ ]:
import os

In [ ]:
num_process = os.cpu_count()
num_process

2

# function arguments



1.   The difference between arguments and parameters
2.   Positional and keyword arguments
3.   Default arguments
4.   Variable-length arguments (*args and **kwargs)
5.   Container unpacking into function arguments
6.   Local vs. global arguments
7.   Parameter passing (by value or by reference?)





In [3]:
def foo(a, b, c):            # params
  print(a, b, c)

In [4]:
foo(1, 2, 3)               # positional args

1 2 3


In [5]:
foo(c=1, b=2, a=3)            # keyword args

3 2 1


In [7]:
foo(1, b=3, c=2)

1 3 2


In [10]:
def foo(a, b, c, d=4):            # params
  print(a, b, c, d)

In [11]:
foo(1,2,3)

1 2 3 4


In [14]:
def foo(a, b, *args, **kwargs):
  print(a, b)
  for arg in args:
    print(arg)
  for key in kwargs:
    print(key, kwargs[key])

In [15]:
foo(1,2,   3, 4, 5, six=6, seven=7)

1 2
3
4
5
six 6
seven 7


In [16]:
foo(1,2,  3,4)

1 2
3
4


In [17]:
def foo(a, b, *, c, d):
  print(a, b, c, d)

In [18]:
foo(1,2, c=4, d=4)

1 2 4 4


In [19]:
def foo(*args, last):
  for arg in args:
    print(arg)
  print(last)

In [20]:
foo(1, 2, 3, last = 100)

1
2
3
100


In [21]:
def foo(a, b, c):
  print(a, b, c)

In [22]:
lst = [1,2,3]

In [24]:
foo(*lst)

1 2 3


In [25]:
tup = (1,2,3)

In [26]:
foo(*tup)

1 2 3


In [27]:
dic = {'a':1, "b":2, 'c':4}

In [28]:
foo(**dic)

1 2 4


In [34]:
def foo():
  x = num
  print("number refernced is:", x)

In [35]:
num = 1

In [36]:
foo()

number refernced is: 1


In [39]:
def foo():
  global num   # global
  x = num
  num = 3
  print("number is now:", x)

In [40]:
foo()

number is now: 3


In [45]:
def foo():
  num = 3     # local
  print(num)

In [46]:
num = 0

In [47]:
foo()

3


In [48]:
print(num)

0


In [49]:
def foo(x):
  x = 5       # local

In [50]:
var = 10        # passing

In [51]:
foo(var)
print(var)        # integer immutable, cannot be changed

10


In [55]:
def foo(lst):      # lst mutable, can be changed
  lst.append(4)
  lst[0] = -100

In [56]:
lst = [1, 2, 3]

In [57]:
foo(lst)

In [58]:
print(lst)

[-100, 2, 3, 4]


In [59]:
def foo(lst):
  lst += [200, 300]

In [60]:
foo(lst)

In [61]:
print(lst)

[-100, 2, 3, 4, 200, 300]


In [62]:
def foo(lst):
  lst = lst + [500, 600]    # slight difference, this not working as above, tricky

In [63]:
foo(lst)

In [64]:
print(lst)

[-100, 2, 3, 4, 200, 300]


# asterisks

In [66]:
zeros = [0,2] * 10
print(zeros)

[0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2]


In [67]:
zeros = (0,2) * 10
print(zeros)

(0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2)


In [68]:
zeros = "AB" * 10
print(zeros)

ABABABABABABABABABAB


In [71]:
def foo(a, b, *args, **kwargs):
  print(a, b)
  for arg in args:
    print(arg)
  for key in kwargs:
    print(key, kwargs[key])

In [72]:
foo(1,2,  3,4,5,  six = 6, seven = 7)

1 2
3
4
5
six 6
seven 7


In [78]:
def foo(a, b, c):
  print(a, b, c)

In [79]:
lst = [0, 1, 2]

In [80]:
foo(*lst)

0 1 2


In [81]:
dic = {'a': 1, "b": 5, 'c': 8}

In [83]:
foo(**dic)

1 5 8


In [84]:
num = [1,2,3,4,5,6]

In [85]:
*beginning, last = num

In [86]:
print(beginning)

[1, 2, 3, 4, 5]


In [87]:
print(last)

6


In [88]:
beginning, *last = num

In [89]:
print(beginning)

1


In [90]:
print(last)

[2, 3, 4, 5, 6]


In [91]:
beginning, *midlle, last = num

In [92]:
print(midlle)

[2, 3, 4, 5]


In [93]:
tup = (1,2,3)
lst = [4,5,6]

In [94]:
new_lst = [*tup, *lst]
print(new_lst)

[1, 2, 3, 4, 5, 6]


In [95]:
tup = (1,2,3)
lst = [4,5,6]
sett = {7,8,9}

In [96]:
new_lst = [*tup, *sett, *lst]
print(new_lst)

[1, 2, 3, 8, 9, 7, 4, 5, 6]


In [97]:
dic_1 = {'a':1, 'b':2}
dic_2 = {'c':3, 'd':4}

In [98]:
new_dic = {**dic_1, **dic_2}
print(new_dic)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


# shallow VS deep copy

### shallow copy:
#### only one level deep

In [103]:
org = 5     # immutable

In [104]:
cpy = org    # not new, only a reference

In [102]:
cpy = 6

In [105]:
print(cpy, org)

5 5


In [106]:
org = [0,1,2,3,4]

In [107]:
cpy = org

In [108]:
cpy[0] = -10

In [109]:
print(cpy, org)

[-10, 1, 2, 3, 4] [-10, 1, 2, 3, 4]


In [110]:
import copy

In [111]:
org = [0,1,2,3,4]

In [112]:
cpy = copy.copy(org)

In [113]:
cpy[0] = -10

In [114]:
print(cpy, org)

[-10, 1, 2, 3, 4] [0, 1, 2, 3, 4]


In [115]:
cpy_1 = org[:]
print(cpy_1, org)

[0, 1, 2, 3, 4] [0, 1, 2, 3, 4]


### deep copy:
#### two levels deep

In [116]:
org = [[0,1,2,3,4], [5,6,7,8,9]]

In [117]:
cpy = copy.copy(org)

In [118]:
cpy[0][1] = -10

In [120]:
print(cpy, org)

[[0, -10, 2, 3, 4], [5, 6, 7, 8, 9]] [[0, -10, 2, 3, 4], [5, 6, 7, 8, 9]]


In [122]:
org = [[0,1,2,3,4], [5,6,7,8,9]]

In [123]:
cpy_1 = copy.deepcopy(org)

In [124]:
cpy_1[0][1] = -10

In [125]:
print(cpy_1, org)

[[0, -10, 2, 3, 4], [5, 6, 7, 8, 9]] [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


In [126]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

In [127]:
p1 = Person('Alex', 25)

In [128]:
p2 = p1

In [129]:
p2.age = 48

In [130]:
print(p2.age, p1.age)

48 48


In [134]:
p1 = Person('Alex', 25)

In [135]:
P2_2 = copy.copy(p1)

In [136]:
p2.age = 80

In [137]:
print(p2.age, p1.age)

80 25


In [139]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

class Company:
  def __init__(self, boss, employee):
    self.boss = boss
    self.employee = employee

In [140]:
p1 = Person('Alex', 55)
p2 = Person('Joe', 27)

In [141]:
company = Company(p1, p2)

In [145]:
company_clone = copy.copy(company)

In [146]:
company_clone.boss.age = 80

In [147]:
print(company_clone.boss.age, company.boss.age)

80 80


In [148]:
p1 = Person('Alex', 55)
p2 = Person('Joe', 27)
company = Company(p1, p2)

In [149]:
company_clone = copy.deepcopy(company)

In [150]:
company_clone.boss.age = 88

In [151]:
print(company_clone.boss.age, company.boss.age)

88 55


# context manager

In [152]:
with open('notes.txt', 'w') as file:
  file.write('some words...')

In [159]:
class ManagedFile():
  def __init__(self, filename):
    self.filename = filename
  
  def __enter__(self):
    print('Enter')
    self.file = open(self.filename, 'w')
    return self.file

  def __exit__(self, exc_type, exc_value, exc_traceback):
    if self.file:
      self.file.close()
    if exc_type is not None:
      print('exception has been handled')
    print('exc:', exc_type, exc_value)
    print('exit')
    return True

In [161]:
with ManagedFile('notes.txt') as file:
  print('do something...')
  file.write("some words...")
  file.somemethod()
print('Continue')

Enter
do something...
exception has been handled
exc: <class 'AttributeError'> '_io.TextIOWrapper' object has no attribute 'somemethod'
exit
Continue


In [162]:
from contextlib import contextmanager

In [163]:
@contextmanager

def open_managed_file(filename):
  f = open(filename, 'w')
  try:
    yield f
  finally:
    f.close()

In [164]:
with open_managed_file('notes.txt') as f:
  f.write('some words...')